# Generated by Django 3.0 on 2020-02-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_auto_20200228_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
